---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
language: zh-CN # 修改为中文
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: 我的导航页

background:  
  image: https://api.vvhan.com/api/bing?size=1920
  blur: sm 
  saturate: 50
  brightness: 50
  opacity: 50
