---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
locale: zh-CN # 修改为中文
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey


# 4 januari 2023 om 13:51:25 PST
format:
  dateStyle: long # 长日期格式
  timeStyle: long # 长时间格式
  timeZone: Asia/Shanghai # 修改为北京时间时区
